<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7Q921NC" failures="2" tests="12" name="com.Myretry.SamplePgm" time="0.037" errors="0" timestamp="2022-03-03T12:01:57 IST" skipped="10">
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.001">
    <failure message="expected [Palam] but found [Paul]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Palam] but found [Paul]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Myretry.SamplePgm.pwdVali(SamplePgm.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pwdVali -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.001">
    <skipped/>
  </testcase> <!-- pwdVali -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.008">
    <skipped/>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.000">
    <skipped/>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.001">
    <skipped/>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.001">
    <skipped/>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.002">
    <skipped/>
  </testcase> <!-- pwdVali -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.003">
    <skipped/>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="usernameValidation" time="0.005">
    <failure message="expected [MSD] but found [Cool]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [MSD] but found [Cool]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Myretry.SamplePgm.usernameValidation(SamplePgm.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- usernameValidation -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.010">
    <skipped/>
  </testcase> <!-- pwdVali -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.001">
    <skipped/>
  </testcase> <!-- pwdVali -->
  <system-out/>
  <testcase classname="com.Myretry.SamplePgm" name="pwdVali" time="0.004">
    <skipped/>
  </testcase> <!-- pwdVali -->
  <system-out/>
</testsuite> <!-- com.Myretry.SamplePgm -->
